package hotel;


import com.itextpdf.text.Chunk;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.table.DefaultTableModel;
import db.Select;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import db.InsertUpdateDelete;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author NIGNOSZY
 */
public class customerCheckOut extends javax.swing.JFrame {

    /**
     * Creates new form customerCheckOut
     */
    public customerCheckOut() {
        initComponents();
        txtName.setEditable(false);
        txtCheckIn.setEditable(false);
        txtCheckOut.setEditable(false);
        txtMobile.setEditable(false);
        txtPerDay.setEditable(false);
        txtDayStay.setEditable(false);
        txtAmount.setEditable(false);
        txtEmail.setEditable(false);
    }
    int id = 0;
    String Query;
    String roomType;
    String bedType;
    String roomNo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRoomNo = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCheckIn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCheckOut = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPerDay = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDayStay = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCheckOut = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/check out.png"))); // NOI18N
        jLabel1.setText("Customer-Check-Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 331, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 88, -1, -1));

        txtRoomNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtRoomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 83, 200, -1));

        btnSearch.setBackground(new java.awt.Color(0, 153, 0));
        btnSearch.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 115, -1, -1));

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 141, 240, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Check-In-Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 115, -1, -1));

        txtCheckIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 141, 240, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Check-Out-Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 115, -1, -1));

        txtCheckOut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 141, 240, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Customer Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 115, -1, -1));

        txtMobile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 141, 240, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Price Per Day");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 173, -1, -1));

        txtPerDay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtPerDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 199, 240, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Number Of Days Stay");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 173, -1, -1));

        txtDayStay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtDayStay, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 199, 240, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Total Amount ");
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 173, -1, -1));

        txtAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 199, 240, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 173, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 199, 240, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobile Number", "Address  ", "Nationality", "Gender", "Email", "SSNumber", "Check-In Date", "Room No.", "Bed Type", "Room Type", "Price/Day"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 293, 1050, 370));

        btnCheckOut.setBackground(new java.awt.Color(0, 153, 0));
        btnCheckOut.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnCheckOut.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckOut.setText("Check-Out");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/all page.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-830, 0, 1920, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        ResultSet rs = Select.getData("select *from customer where checkOut is NULL");
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        try
        {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),rs.getString(13)});
            }
            rs.close();
        }
            
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String roomNo = txtRoomNo.getText();
        try
        {
            ResultSet rs = Select.getData("select *from customer where roomNo = '"+roomNo+"' and checkout is NULL");
            if(rs.next())
            {
                txtRoomNo.setEditable(false);
                id = rs.getInt(1);
                txtName.setText(rs.getString(2));
                txtCheckIn.setText(rs.getString(9));
                txtMobile.setText(rs.getString(3));
                txtPerDay.setText(rs.getString(13));
                
                SimpleDateFormat myFormat = new SimpleDateFormat("yyyy/MM/dd");
                Calendar cal = Calendar.getInstance();
                txtCheckOut.setText(myFormat.format(cal.getTime()));
                
                String dateBeforeString = rs.getString(9);
                java.util.Date dateBefore = myFormat.parse(dateBeforeString);
                String dateAfterString = myFormat.format(cal.getTime());
                java.util.Date dateAfter = myFormat.parse(dateAfterString);
                
                long difference = dateAfter.getTime() - dateBefore.getTime();
                int noOfDayStay = (int) (difference/(1000*60*60*24));
                if(noOfDayStay==0)
                
                    noOfDayStay = 1;
                txtDayStay.setText(String.valueOf(noOfDayStay));
                float price = Float.parseFloat(txtPerDay.getText()); // Declare price here
                txtAmount.setText(String.valueOf(noOfDayStay * price));
                txtEmail.setText(rs.getString(7));
                roomType = rs.getString(12);
                bedType = rs.getString(11);
            }
            else 
               JOptionPane.showMessageDialog(null, "Room Number Not Booking or Exit");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        new customerCheckOut().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        String name = txtName.getText();
        String mobileNum = txtMobile.getText();
        String email = txtEmail.getText();
        String checkOut = txtCheckOut.getText();
        String numberDayStay = txtDayStay.getText();
        String totalAmount = txtAmount.getText();
        String roomNo = txtRoomNo.getText(); // Ensure it's properly declared

        String Query = "UPDATE customer SET numberDayStay = '"+numberDayStay+"', totalAmount='"+totalAmount+"', checkOut='"+checkOut+"' WHERE id = '"+id+"'";
        InsertUpdateDelete.setData(Query, "");

        Query = "UPDATE room SET Status = 'Not booked' WHERE roomNo='"+roomNo+"'";
        InsertUpdateDelete.setData(Query, "");

        String path = "C:\\Hotel Bill\\" + id + ".pdf";

        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path)); // Removed duplicate id concatenation
            doc.open();
            
            Font titleFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
            Font headerFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
            Font bodyFont = new Font(Font.FontFamily.HELVETICA, 11);

            Paragraph paragraph1 = new Paragraph("SOMBOON HOTEL\n\n", titleFont);
    paragraph1.setAlignment(Element.ALIGN_CENTER);
    doc.add(paragraph1);

    // ===== Line =====
    Paragraph line = new Paragraph("------------------------------------------------------------------------------------------------------------------------");
    doc.add(line);

    // ===== Customer Section =====
    Paragraph paragraph3 = new Paragraph();
    paragraph3.add(new Chunk("Bill ID: ", headerFont));
    paragraph3.add(new Chunk(id + "\n\n", bodyFont));

    paragraph3.add(new Chunk("Customer Details\n", headerFont));
    paragraph3.add(new Chunk(
            "Name          : " + name + "\n" +
            "Mobile Number : " + mobileNum + "\n" +
            "Email         : " + email + "\n", bodyFont
    ));
    doc.add(paragraph3);

    doc.add(line);

    // ===== Room Section =====
    Paragraph paragraph4 = new Paragraph();
    paragraph4.add(new Chunk("Room Details\n", headerFont));
    paragraph4.add(new Chunk(
            "Room Number   : " + roomNo + "\n" +
            "Room Type     : " + roomType + "\n" +
            "Bed Type      : " + bedType + "\n" +
            "Price / Day   : " + txtPerDay.getText() + "\n", bodyFont
    ));
    doc.add(paragraph4);

    doc.add(line);

    // ===== Table Summary =====
    PdfPTable tb1 = new PdfPTable(4);
    tb1.setWidthPercentage(100);
    tb1.setSpacingBefore(8f);
    tb1.setSpacingAfter(8f);

    // (Optional) set column widths to look better
    tb1.setWidths(new float[]{2.2f, 2.2f, 2.0f, 2.6f});

    // Header row (looks nicer)
    PdfPCell h1 = new PdfPCell(new Phrase("Check-In", headerFont));
    PdfPCell h2 = new PdfPCell(new Phrase("Check-Out", headerFont));
    PdfPCell h3 = new PdfPCell(new Phrase("Days", headerFont));
    PdfPCell h4 = new PdfPCell(new Phrase("Total Amount", headerFont));

    h1.setHorizontalAlignment(Element.ALIGN_CENTER);
    h2.setHorizontalAlignment(Element.ALIGN_CENTER);
    h3.setHorizontalAlignment(Element.ALIGN_CENTER);
    h4.setHorizontalAlignment(Element.ALIGN_CENTER);

    tb1.addCell(h1);
    tb1.addCell(h2);
    tb1.addCell(h3);
    tb1.addCell(h4);

    // Data row
    tb1.addCell(new Phrase(txtCheckIn.getText(), bodyFont));
    tb1.addCell(new Phrase(txtCheckOut.getText(), bodyFont));

    PdfPCell daysCell = new PdfPCell(new Phrase(txtDayStay.getText(), bodyFont));
    daysCell.setHorizontalAlignment(Element.ALIGN_CENTER);
    tb1.addCell(daysCell);

    PdfPCell totalCell = new PdfPCell(new Phrase(txtAmount.getText(), bodyFont));
    totalCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
    tb1.addCell(totalCell);

    doc.add(tb1);

    doc.add(line);

    // ===== Footer =====
    Paragraph paragraph5 = new Paragraph(
            "\nThank you for using our service. Please come visit again next time.",
            new Font(Font.FontFamily.HELVETICA, 10, Font.ITALIC)
    );
    paragraph5.setAlignment(Element.ALIGN_CENTER);
    doc.add(paragraph5);

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
} finally {
    doc.close();
}

        int a = JOptionPane.showConfirmDialog(null, "Do you want to print the bill?", "Select", JOptionPane.YES_NO_OPTION);
            if (a == 0) 
            {
                try 
            {
                if ((new File ("C:\\Hotel Bill\\"+id+".pdf")).exists()) 
                {
                    Process p = Runtime
                    .getRuntime()
                    .exec("rundll32 url.dll,FileProtocolHandler C:\\Hotel Bill\\"+id+".pdf");
                } 
                else 
                System.out.println("File does not exist.");
            } 
            catch (Exception e) 
            {
               JOptionPane.showMessageDialog(null, e);
            }
        }
        setVisible(false);
        new customerCheckOut().setVisible(true);
    }//GEN-LAST:event_btnCheckOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerCheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCheckIn;
    private javax.swing.JTextField txtCheckOut;
    private javax.swing.JTextField txtDayStay;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPerDay;
    private javax.swing.JTextField txtRoomNo;
    // End of variables declaration//GEN-END:variables
}
