package hotel;


import db.Select;
import db.InsertUpdateDelete;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author NIGNOSZY
 */
public class customerCheckIn extends javax.swing.JFrame {

    /**
     * Creates new form customerCheckIn
     */
    public customerCheckIn() {
        initComponents();
        txtDate.setEditable(false);
        txtPrice.setEditable(false);
        SimpleDateFormat myFormat = new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal = Calendar.getInstance();
        txtDate.setText(myFormat.format(cal.getTime()));
    }
    
    String bedType;
    String roomType;
    String roomNo;
    String price;
    
    public void roomDetails()
    {
        ckbRoomNo.removeAllItems();
        txtPrice.setText("");
        bedType = (String)ckbBed.getSelectedItem();
        roomType = (String)ckbRoomType.getSelectedItem();
        try
        {
            ResultSet rs = Select.getData("select *from room where bedType = '" + bedType + "' and roomType = '" + roomType + "' and status = 'Not Booked'");
            while(rs.next())
            {
                ckbRoomNo.addItem(rs.getString(1));
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNation = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ckbGender = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSsNum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ckbRoomNo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        ckbRoomType = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        ckbBed = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnAllote = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtSsNum1 = new javax.swing.JTextField();
        txtSsNum2 = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/check in.png"))); // NOI18N
        jLabel1.setText("Customer-Check-In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/close.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 78, 56, -1));

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 118, 240, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel3.setText("Mobile Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 156, 152, -1));

        txtMobile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 196, 240, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 234, 152, -1));

        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 276, 240, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel5.setText("Nationality");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 314, 152, -1));

        txtNation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtNation, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 354, 240, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 392, 152, -1));

        ckbGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        ckbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbGenderActionPerformed(evt);
            }
        });
        getContentPane().add(ckbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 432, 240, -1));

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 152, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 513, 240, -1));

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel8.setText("Social securyty Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 78, -1, -1));

        txtSsNum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSsNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSsNumActionPerformed(evt);
            }
        });
        getContentPane().add(txtSsNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 118, 240, -1));

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel9.setText("Check-In Date(Today)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 156, -1, -1));

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel10.setText("Room Number");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, -1, -1));

        ckbRoomNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckbRoomNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbRoomNoActionPerformed(evt);
            }
        });
        getContentPane().add(ckbRoomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 240, -1));

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel11.setText("Room Type");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 156, -1, -1));

        ckbRoomType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckbRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard Room", "Deluxe Room" }));
        ckbRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbRoomTypeActionPerformed(evt);
            }
        });
        getContentPane().add(ckbRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 196, 240, -1));

        jLabel12.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel12.setText("Bed Type");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, -1, -1));

        ckbBed.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckbBed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Bed", "Twin Bed", "Triple Bed" }));
        ckbBed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbBedActionPerformed(evt);
            }
        });
        getContentPane().add(ckbBed, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 240, -1));

        jLabel13.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel13.setText("Price");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 306, -1, -1));

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 346, 240, -1));

        btnAllote.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnAllote.setText("Allote Room");
        btnAllote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlloteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAllote, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 410, -1, -1));

        btnClear.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(962, 410, -1, -1));

        txtSsNum1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSsNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSsNum1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSsNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 118, 240, -1));

        txtSsNum2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSsNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSsNum2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSsNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 118, 240, -1));

        txtDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 230, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/all page.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void ckbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbGenderActionPerformed

    private void txtSsNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSsNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSsNumActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        setVisible(false);
        new customerCheckIn().setVisible(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void ckbRoomNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbRoomNoActionPerformed
        roomNo = (String)ckbRoomNo.getSelectedItem();
        try
        {
            ResultSet rs = Select.getData("select *from room where roomNo = '"+roomNo+"'");
            while(rs.next())
            {
                txtPrice.setText(rs.getString(4));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ckbRoomNoActionPerformed

    private void ckbRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbRoomTypeActionPerformed
        roomDetails();
    }//GEN-LAST:event_ckbRoomTypeActionPerformed

    private void ckbBedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbBedActionPerformed
        roomDetails();
    }//GEN-LAST:event_ckbBedActionPerformed

    private void btnAlloteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlloteActionPerformed
        int id = 1;
String name = txtName.getText();
String mobileNum = txtMobile.getText();
String address = txtAddress.getText();
String nationality = txtNation.getText();
String gender = (String) ckbGender.getSelectedItem();
String email = txtEmail.getText();
String ssNum = txtSsNum.getText();
String checkIn = txtDate.getText();
String bedType = (String) ckbBed.getSelectedItem();
String roomType = (String) ckbRoomType.getSelectedItem();
String roomNo = (String) ckbRoomNo.getSelectedItem();
String price = txtPrice.getText(); 
String Query = "select max(id) from customer";

try {
    ResultSet rs = Select.getData(Query);
    while (rs.next())
        id = rs.getInt(1);
    id = id + 1;

    if (!price.equals("")) 
    {
        Query = "update room set status='Booked' where roomNo='"+roomNo+"'";
        InsertUpdateDelete.setData(Query, "");
        Query = "insert into customer(id,name,mobileNum,address,nationality,gender,email,ssNum,checkIn,roomNo,bedType,roomType,pricePerDay) values("+id+",'"+name+"','"+mobileNum+"','"+address+"','"+nationality+"','"+gender+"','"+email+"','"+ssNum+"','"+checkIn+"','"+roomNo+"','"+bedType+"','"+roomType+"','"+price+"')";
        
        InsertUpdateDelete.setData(Query, "Customer Check-in Successful");
        setVisible(false);
        new customerCheckIn().setVisible(true);
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}

    }//GEN-LAST:event_btnAlloteActionPerformed

    private void txtSsNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSsNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSsNum1ActionPerformed

    private void txtSsNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSsNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSsNum2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerCheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllote;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JComboBox<String> ckbBed;
    private javax.swing.JComboBox<String> ckbGender;
    private javax.swing.JComboBox<String> ckbRoomNo;
    private javax.swing.JComboBox<String> ckbRoomType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNation;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSsNum;
    private javax.swing.JTextField txtSsNum1;
    private javax.swing.JTextField txtSsNum2;
    // End of variables declaration//GEN-END:variables
}
/*
int id = 1;
String name = txtName.getText();
String mobileNum = txtMobile.getText();
String address = txtAddress.getText();
String nationality = txtNation.getText();
String gender = (String) ckbGender.getSelectedItem();
String email = txtEmail.getText();
String ssNum = txtSsNum.getText();
String checkIn = txtDate.getText();
String bedType = (String) ckbBed.getSelectedItem();
String roomType = (String) ckbRoomType.getSelectedItem();
String roomNo = (String) ckbRoomNo.getSelectedItem();
String price = txtPrice.getText(); 
String Query = "select max(id) from customer";

try {
    ResultSet rs = Select.getData(Query);
    while (rs.next())
        id = rs.getInt(1);
    id = id + 1;

    if (!price.equals("")) 
    {
        Query = "update room set status='Booked' where roomNo='"+roomNo+"'";
        InsertUpdateDelete.setData(Query, "");
        Query = "insert into customer(id,name,mobileNum,address,nationality,gender,email,ssNum,checkIn,roomNo,bedType,roomType,pricePerDay) values("+id+",'"+name+"','"+mobileNum+"','"+address+"','"+nationality+"','"+gender+"','"+email+"','"+ssNum+"','"+checkIn+"','"+roomNo+"','"+bedType+"','"+roomType+"','"+price+"')";
        
        InsertUpdateDelete.setData(Query, "Customer Check-in Successful");
        setVisible(false);
        new customerCheckIn().setVisible(true);
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}
*/